### ISSUE TITLE
Sandhi Method. 

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/samasasplitter#8]
@drdhaval2785 

Thanks a lot for the code and spending time to help. Would appreciate some more of your help:

Please clarify if I've understood your sandhi technique correctly

```
lstrep = [('A',('A','aa','aA','Aa','AA','As')),('I',('I','ii','iI','Ii','II')),('U',('U','uu','uU','Uu','UU')),('F',('F','ff','fx','xf','Fx','xF','FF')),('e',('e','ea','ai','aI','Ai','AI')),('o',('o','oa','au','aU','Au','AU','aH','aHa','as')),('E',('E','ae','Ae','aE','AE')),('O',('O','ao','Ao','aO','AO')),('ar',('af','ar')),('d',('t','d')),('H',('H','s')),('S',('S','s','H')),('M',('m','M')),('y',('y','i','I')),('N',('N','M')),('Y',('Y','M')),('R',('R','M')),('n',('n','M')),('m',('m','M')),('v',('v','u','U')),('r',('r','s','H')),]
```
This is converted to a dict, and each letter that matches a key is replaced (optionally) by each of the replacements. 
eg: rAmeha, split at e becomes rAmeha,rAmeaha,rAmaiha,ramaIha,ramAiha,ramAIha

Then you take the outer product of all such replacements using itertools.product, and split each of them. 
Did I get that right?

If so, a couple of questions:
1) Right context is not used at all, as I could gather. So
     ramogacCati = ramasgacCati (one of the options)
     ramokathayati = ramaskathayati (one of the options)
    the latter shouldn't happen. (Did I get this wrong?)
2) Neither is left context, so 
    ---ara--- could be split as ---as a--- which will not happen in reality (would be ---o---) 
3) I don't see things like jhalaM jaSo'nte. How does vAgarthau get split into vAk + arthau? 

I would like to reuse as much as possible, so If I can pick this directly, I would like to. Maybe I'm missing an extra step somewhere?

**Comment by drdhaval2785** [comment]
1,2

Not used left or right context at all.
In fact I am yet to find a non recursive way of using these contexts. I am
sure there must be some previously thought optimized algorithm.

**Comment by kmadathil** [comment]
Thanks. I'll close this here and open another issue on kmadathil/sanksrit_parser to discuss this further

**Comment by gasyoun** [comment]
> In fact I am yet to find a non recursive way of using these contexts. I am
sure there must be some previously thought optimized algorithm.

Huet's code checked?
